/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'lari' at '11/29/14 9:33 AM' with Gradle 2.2.1
 *
 * @author lari, @date 11/29/14 9:33 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
