language: groovy
jdk:
- oraclejdk7
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
script: ./gradlew test
install: /bin/true
after_failure: ./travis-after-failure.sh
