/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'lari' at '11/29/14 9:33 AM' with Gradle 2.2.1
 *
 * @author lari, @date 11/29/14 9:33 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }

    def "this fails"() {
    	expect:
    	"Hello World!" == "Hello there!"
    }

    def "this throws an exception"() {
    	when:
    	throw new RuntimeException("Here you are")
    	then:
    	1 == 1
    }
}
